spring:
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop

  datasource:
    url: jdbc:postgresql://localhost:5432/CLessT1
    username: ${DatabaseLogin}
    password: ${DatabasePass}
    driver-class-name: org.postgresql.Driver
    tomcat:
      max-active: 250